let waterValues = {
    residents : "0",
    averageShowerLength : "0",
    lowFlowShowerHeads : "false",
    baths : "0",
    bathFrequency : "daily",
    bathroomFaucetRunTime : "0",
    lowFlowBathroomFaucet : "false",
    toiletFlushFrequency : "0",
    lowFlowToilets : "false",
    kitchenFaucetRunTime : "0",
    lowFlowKitchenFaucet : "false",
    oldSchoolDishwasherLoads : "0",
    oldSchoolDishwasherFrequency : "0",
    efficientDishwasherLoads : "0",
    efficientDishwasherFrequency : "0",
    handWashingLoads : "0",
    handWashingFrequency : "0", 
    trashThemLoads : "0",
    trashThemFrequency : "0",
    oldSchoolWashingMachineFrequency : "0",
    oldSchoolWashingMachineLoads : "0",
    efficientWashingMachineFrequency : "0",
    efficientWashingMachineLoads : "0",
}